'use client';
import {useEffect,useState} from 'react';
import {Monitor,Cloud,FileText,Volume2,Scissors,RefreshCw} from 'lucide-react';
import {NativeSelect} from '@/components/ui/native-select';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Button} from '@/components/ui/button';
import {toast} from 'sonner';
import {ModelSchema,modelTask,supportsTask,type Model,type Project} from '@/lib/core';
import {localModels,localRequest} from '@/lib/local-ai';
import {Transcript,momentMessages,parseMoments} from '@/lib/moments';
import {downloadBlob} from '@/lib/video';
const jobs=[{id:'script',name:'Write the script',icon:FileText,help:'Turns your source and saved instructions into scenes.'},{id:'moments',name:'Find strong moments',icon:Scissors,help:'Selects clips from a transcript with real timestamps.'},{id:'voice',name:'Speak the words',icon:Volume2,help:'Makes narration from the script you have reviewed.'}] as const;
async function post(path:string,payload:unknown){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok){const d=await r.json() as {error?:string};throw Error(d.error||'The service could not complete this request.');}return r;}
export default function ModelWorkbench({models,project,onProject,onModels}:{models:Model[],project:Project,onProject:(p:Partial<Project>)=>void,onModels:(m:Model[])=>void}){
 const [local,setLocal]=useState<string[]>([]),[status,setStatus]=useState('Checking LM Studio…'),[busy,setBusy]=useState(''),[key,setKey]=useState(''),[catalog,setCatalog]=useState<{id:string,name:string}[]>([]);
 const [edit,setEdit]=useState<Model>({id:'',name:'',provider:'local',model:'',task:'script'}),[transcript,setTranscript]=useState(''),[moments,setMoments]=useState<{start:number,end:number,title:string,reason:string}[]>([]);
 async function discover(){setStatus('Checking LM Studio…');try{const ids=await localModels();setLocal(ids);setStatus(ids.length?`LM Studio found · ${ids.length} model${ids.length===1?'':'s'} available`:'LM Studio is running. Load or download a text model there.');}catch(e){setLocal([]);setStatus((e as Error).message);}}
 useEffect(()=>{discover();},[]);
 const choice=(job:string)=>job==='script'?project.modelId:job==='voice'?project.voiceModelId||'':project.momentModelId||'';
 const assign=(job:string,id:string)=>onProject(job==='script'?{modelId:id}:job==='voice'?{voiceModelId:id}:{momentModelId:id});
 async function save(){setBusy('save');try{const value={...edit,id:edit.id||crypto.randomUUID(),name:edit.name||edit.model};ModelSchema.parse(value);if(!supportsTask(value,value.task||'script'))throw Error('This service does not support the chosen job.');if(value.task==='voice'&&!value.voice?.trim())throw Error('Add a voice name or voice ID.');const saved=await (await post('/api/items',{id:value.id,kind:'model',revision:value.revision,value})).json() as Model;onModels([...models.filter(m=>m.id!==saved.id),saved]);assign(saved.task||'script',saved.id);setEdit({...edit,id:'',name:'',revision:undefined});toast.success('Model saved and selected for this project. Save the project to keep this choice.');}catch(e){toast.error((e as Error).message);}finally{setBusy('');}}
 async function speech(){setBusy('voice');try{const m=models.find(m=>m.id===project.voiceModelId);if(!m||!supportsTask(m,'voice'))throw Error('Choose a saved voice model first.');const text=project.scenes.map(s=>s.narration).join('\n\n');if(!text||text.length>6000)throw Error('Add a script of 1–6,000 characters first.');let response;if(m.provider==='local-voice')response=await localRequest('/audio/speech',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:m.model,voice:m.voice,input:text,response_format:'mp3'})},true);else response=await post('/api/speech',{modelId:m.id,text,key});const blob=await response.blob();if(blob.size>20*1024*1024)throw Error('The narration is too large. Shorten the script.');const data=new FormData();data.append('file',new File([blob],'narration.mp3',{type:'audio/mpeg'}));const r=await fetch('/api/audio',{method:'POST',body:data});const result=await r.json() as {id:string,error?:string};if(!r.ok){downloadBlob(blob,'narration.mp3');throw Error('Narration downloaded, but could not be saved to the project. Upload the recording in Script & voice.');}onProject({audioId:result.id});toast.success('Narration added. Open Script & voice to listen, then save the project.');}catch(e){toast.error((e as Error).message);}finally{setBusy('');}}
 async function findMoments(){setBusy('moments');setMoments([]);try{const segments=Transcript.parse(JSON.parse(transcript));if(JSON.stringify(segments).length>80000)throw Error('Use a transcript under 80,000 characters.');const m=models.find(m=>m.id===project.momentModelId);if(!m||!supportsTask(m,'moments'))throw Error('Choose a saved model for finding moments.');let result:{moments:{start:number,end:number,title:string,reason:string}[]};if(m.provider==='local'){if(m.model==='auto')throw Error('Select an exact LM Studio model first.');const r=await (await localRequest('/chat/completions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:m.model,messages:momentMessages(segments),response_format:{type:'json_object'},max_tokens:2500})})).json() as {choices?:{message?:{content?:string}}[]};result=parseMoments(r.choices?.[0]?.message?.content||'',segments);}else result=await (await post('/api/moments',{modelId:m.id,segments,key})).json() as typeof result;setMoments(result.moments);}catch(e){toast.error((e as Error).message);}finally{setBusy('');}}
 return <div className="model-workbench"><div className="page-heading"><div><div className="eyebrow">ONE JOB. THE RIGHT MODEL.</div><h1>Models & voices</h1><p>Choose what writes, finds clips and speaks. Each job can use your computer or an online service.</p></div></div>
 <div className="task-routing">{jobs.map(j=><section className="nbs-card route-card" key={j.id}><h2><j.icon size={20}/>{j.name}</h2><p>{j.help}</p><label className="field-label">Model for this project<NativeSelect className="nbs-select" value={choice(j.id)} onChange={e=>assign(j.id,e.target.value)}><option value="">Choose a saved model</option>{models.filter(m=>supportsTask(m,j.id)).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</NativeSelect></label><span className="helper">Only this job uses this choice. Other jobs keep their models. Start with a local model if it is already available; choose an online service if you have an account. Save the project to keep this choice.</span></section>)}</div>
 <section className="nbs-card integration-panel"><div className="connection-row"><h2><Monitor size={21}/> Your computer</h2><Button className="nbs-button" onClick={discover}><RefreshCw size={16}/>Check LM Studio</Button></div><p className="status-copy" role="status">{status}</p><p className="helper">No address or key to enter. ClipForge checks LM Studio’s usual local address. Start the server in LM Studio and allow browser access there. Your computer stays on while it works. Local inference stays on your computer; saving a project stores its source and script in your private online workspace.</p></section>
 <section className="nbs-card integration-panel"><h2>{edit.id?'Edit a model':'Add a model for a job'}</h2><div className="two-cols"><label className="field-label">Job<NativeSelect className="nbs-select" value={edit.task||'script'} onChange={e=>{const task=e.target.value as Model['task'];setEdit({...edit,task,provider:task==='voice'?'local-voice':'local',model:'',voice:''});setCatalog([]);}}>{jobs.map(j=><option key={j.id} value={j.id}>{j.name}</option>)}</NativeSelect></label><label className="field-label">Service<NativeSelect className="nbs-select" value={edit.provider} onChange={e=>{setEdit({...edit,provider:e.target.value as Model['provider'],model:''});setCatalog([]);}}>{(edit.task==='voice'?[['local-voice','My computer · OpenAI-compatible TTS'],['openai','Online · OpenAI'],['elevenlabs','Online · ElevenLabs']]:[['local','My computer · LM Studio'],['openai','Online · OpenAI'],['openrouter','Online · OpenRouter'],['groq','Online · Groq']]).map(([id,name])=><option key={id} value={id}>{name}</option>)}</NativeSelect></label></div>
 <details className="details"><summary>Help me choose a job and service</summary><p>Write the script: turns ideas into words. Find strong moments: reads a transcript and chooses clip times. Speak the words: makes audio from a finished script.</p><p>LM Studio: uses a model on your computer. OpenAI: uses your OpenAI account. OpenRouter: uses a model offered through your OpenRouter account. Groq: uses your Groq account. ElevenLabs: uses your ElevenLabs voice and account. Local speech: uses a separate voice program running on your computer.</p><p>Recommended: start with LM Studio for writing if you already use it. For speech, choose a service or local voice program you already have. Changing a service does not buy a model or start a download.</p></details><div className="two-cols"><label className="field-label">Name you will recognize<Input className="nbs-input" value={edit.name} maxLength={80} onChange={e=>setEdit({...edit,name:e.target.value})} placeholder="For example, My story writer"/><span className="helper">A label for your saved choice. Use a short name that explains its job.</span></label><label className="field-label">{edit.provider==='local'?'Model from LM Studio':'Model ID from the service'}{edit.provider==='local'?<NativeSelect className="nbs-select" value={edit.model} onChange={e=>setEdit({...edit,model:e.target.value})}><option value="">Choose a detected model</option>{local.map(id=><option key={id}>{id}</option>)}</NativeSelect>:<Input className="nbs-input" list="provider-models" value={edit.model} maxLength={180} onChange={e=>setEdit({...edit,model:e.target.value})} placeholder="Exact model ID"/>}<span className="helper">Choose an exact name returned by the service. For online models, enter the service key below and load its list. Model support and charges depend on the service.</span></label></div><datalist id="provider-models">{catalog.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</datalist>
 {edit.task==='voice'&&<label className="field-label">Voice name or ID<Input className="nbs-input" value={edit.voice||''} maxLength={180} onChange={e=>setEdit({...edit,voice:e.target.value})}/><span className="helper">Use a voice supported by this service. ElevenLabs uses a voice ID. Local Kokoro-compatible servers commonly use names such as af_heart.</span></label>}
 {edit.provider==='local-voice'&&<p className="helper">Requires a separate speech server on port 8880 with browser access enabled. LM Studio’s text models do not generate narration. The included Python maker also supports Kokoro without an API server.</p>}
 <Button className="nbs-button nbs-button--primary" disabled={!!busy||!edit.model} onClick={save}>Save model and use it</Button></section>
 <section className="nbs-card integration-panel"><h2><Cloud size={21}/> Online service key</h2><p>For your own service account, enter its key for this visit. It is sent only to the selected service and is not saved. Generating content may use paid credit. There is no automatic switch to a paid model.</p><label className="field-label">Key for the service you are about to use<Input className="nbs-input" type="password" autoComplete="off" value={key} maxLength={500} onChange={e=>setKey(e.target.value)}/></label><Button className="nbs-button" disabled={!!busy||!key||['local','local-voice'].includes(edit.provider)} onClick={async()=>{setBusy('catalog');try{setCatalog((await (await post('/api/models',{provider:edit.provider,key})).json() as {models:{id:string,name:string}[]}).models);toast.success('Model list loaded. Open the model ID field to choose.');}catch(e){toast.error((e as Error).message);}finally{setBusy('');}}}>Load models from the selected service</Button></section>
 <section className="nbs-card integration-panel"><h2>Saved models</h2><table className="model-table"><thead><tr><th>Name</th><th>Job</th><th>Service</th><th>Change</th></tr></thead><tbody>{models.map(m=><tr key={m.id}><td className="model-code">{m.name}<p className="helper">{m.model}</p></td><td>{jobs.find(j=>j.id===modelTask(m))?.name}</td><td>{m.provider}</td><td><Button className="nbs-button" onClick={()=>{setEdit({...m});setCatalog([]);}}>Edit</Button></td></tr>)}</tbody></table></section>
 <section className="nbs-card integration-panel"><h2>Make narration for “{project.title}”</h2><p>{project.scenes.length?`${project.scenes.length} scenes ready. Uses the voice model selected above.`:'Write a script in Create a video first.'}</p><Button className="nbs-button nbs-button--primary" disabled={!!busy||!project.scenes.length||!project.voiceModelId} onClick={speech}>{busy==='voice'?'Making narration…':'Generate narration'}</Button></section>
 <section className="nbs-card integration-panel"><h2>Find moments in a transcript</h2><p>Paste timestamped transcript JSON. This selects clip boundaries; rendering the source video still uses the clipping engine in engine-v02.</p><label className="field-label">Transcript segments · seconds<Textarea className="nbs-textarea" rows={6} maxLength={80000} value={transcript} onChange={e=>setTranscript(e.target.value)} placeholder={'[{"start":0,"end":15,"text":"The opening words…"}]'}/></label><div className="actions"><Button className="nbs-button" onClick={()=>{setTranscript(JSON.stringify([{start:0,end:15,text:'A small habit can change how you begin the day.'},{start:15,end:30,text:'Before reaching for your phone, open the curtains and take a breath.'}],null,2));setMoments([]);}}>Load an example transcript</Button><Button className="nbs-button" onClick={()=>{setTranscript('');setMoments([]);}}>Clear transcript</Button></div><p className="helper">Paste one JSON list, choose your moment-finding model above, then select Find strong moments. Try the example first if you are unsure of the format. Each segment needs start, end and text. Use ordered, non-overlapping timestamps. Clips must be 10–120 seconds.</p><Button className="nbs-button nbs-button--primary" disabled={!!busy||!transcript||!project.momentModelId} onClick={findMoments}>{busy==='moments'?'Reading the transcript…':'Find strong moments'}</Button>{moments.map((m,i)=><article className="scene-editor" key={i}><h3>{m.title} · {m.start}–{m.end} seconds</h3><p>{m.reason}</p></article>)}{!!moments.length&&<Button className="nbs-button" onClick={()=>downloadBlob(new Blob([JSON.stringify({moments},null,2)],{type:'application/json'}),'clipforge-moments.json')}>Download selected moments</Button>}</section>
 <p className="helper">Motion uses the three built-in templates. Image generation, speech transcription in the web editor and automatic social posting are not connected yet.</p>
 </div>;
}
