'use client';
import { useEffect,useRef,useState,useMemo,type ReactNode } from 'react';
import { Plus,Clapperboard,FolderOpen,BookOpen,SlidersHorizontal,Link2,ArrowUpRight,ArrowRight,Check,Play,Pause,Download,Upload,Sparkles,Save,ChevronRight,FileText,Monitor,Cloud,Trash2,RefreshCw,Volume2,Copy,CheckCircle2,LoaderCircle } from 'lucide-react';
import { SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger } from '@/components/ui/sidebar';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog,DialogContent,DialogTitle,DialogDescription,DialogHeader } from '@/components/ui/dialog';
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from '@/components/ui/alert-dialog';
import { Progress } from '@/components/ui/progress';
import { Toaster,toast } from 'sonner';
import { defaultSkills,defaultModels,chooseSkills,newProject,scriptScenes,ProjectSchema,SkillSchema,ModelSchema,type Skill,type Model,type Project,type Scene } from '@/lib/core';
import ModelWorkbench from './model-workbench';
import { localGenerate } from '@/lib/local-ai';
import { modelTask } from '@/lib/core';
import { drawFrame,downloadBlob,recordVideo } from '@/lib/video';
const styles=[{id:'story',name:'Story cards',description:'Bold captions and a clear beginning, middle and end.',tag:'Great for stories',color:'purple'},{id:'explainer',name:'Quick explainer',description:'Turn a useful idea into easy-to-follow points.',tag:'Great for articles',color:'lime'},{id:'quote',name:'Words that stay',description:'Give a few thoughtful lines room to breathe.',tag:'Great for short thoughts',color:'dark'}] as const;
const demo:Scene[]=[{heading:'A tiny habit.\nA different day.',narration:'Before you pick up your phone tomorrow, open the curtains and take one slow breath.'},{heading:'Make room for a pause.',narration:'You do not have to change your whole routine. Start with one small moment that belongs to you.'},{heading:'Small is a good start.',narration:'Try it once. Notice how it feels. Keep what works for you.'}];
type View='create'|'projects'|'skills'|'models'|'publish'|'agents';
async function api<T={ok:boolean}>(path:string,options?:RequestInit):Promise<T>{const r=await fetch(path,options);const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'This could not be completed. Please try again.');return d as T;}
function jsonOptions(value:unknown,method='POST'){return {method,headers:{'Content-Type':'application/json'},body:JSON.stringify(value)};}
function Field({label,help,children,details}: {label:string,help:string,children:ReactNode,details?:ReactNode}){return <div className="field"><label className="field-label">{label}{children}</label><p className="helper">{help}</p>{details&&<details className="details"><summary>Help me choose</summary><div>{details}</div></details>}</div>;}
function Pill({children,tone='plain'}:{children:ReactNode,tone?:string}){return <span className={'pill '+tone}>{children}</span>;}
function Choice({value,onChange,options,label}:{value:string,onChange:(v:string)=>void,options:{value:string,label:string}[],label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="choice" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;}
export default function Studio(){
 const [theme,setTheme]=useState('light');
 const [view,setView]=useState<View>('create'),[tab,setTab]=useState('source');const [project,setProject]=useState<Project>(()=>({...newProject(),id:'new-draft'}));
 const [projects,setProjects]=useState<Project[]>([]),[skills,setSkills]=useState<Skill[]>(defaultSkills),[models,setModels]=useState<Model[]>(defaultModels);
 const [loaded,setLoaded]=useState(false),[loadError,setLoadError]=useState(''),[busy,setBusy]=useState(''),[dirty,setDirty]=useState(false),[key,setKey]=useState('');
 const [skillEdit,setSkillEdit]=useState<Skill|null>(null),[remove,setRemove]=useState<{kind:string,item:any}|null>(null),[guide,setGuide]=useState(false);
 const [playing,setPlaying]=useState(false),[time,setTime]=useState(0),[exporting,setExporting]=useState(false),[progress,setProgress]=useState(0);const [search,setSearch]=useState('');
 const canvas=useRef<HTMLCanvasElement>(null),audio=useRef<HTMLAudioElement>(null),abortRef=useRef<AbortController|null>(null),sourceFile=useRef<HTMLInputElement>(null),skillFile=useRef<HTMLInputElement>(null),bundleFile=useRef<HTMLInputElement>(null);
 useEffect(()=>{const t=localStorage.getItem('clipforge-theme')||'light';setTheme(t);document.documentElement.dataset.theme=t;},[]);
 const selected=useMemo(()=>chooseSkills(skills,project),[skills,project]);const model=models.find(m=>m.id===project.modelId)||models.find(m=>modelTask(m)==='script')||defaultModels[0];const scenes=project.scenes.length?project.scenes:demo;const audioUrl=project.audioId?'/api/audio?id='+encodeURIComponent(project.audioId):undefined;
 const change=(patch:Partial<Project>)=>{setProject(p=>({...p,...patch}));setDirty(true);};
 async function refresh(){try{setLoadError('');const d=await api<{projects:Project[],skills:Skill[],models:Model[]}>('/api/state');setProjects(d.projects);setSkills(d.skills);setModels(d.models);setLoaded(true);}catch(e){setLoadError((e as Error).message);}}
 useEffect(()=>{refresh();},[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty||exporting){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty,exporting]);
 useEffect(()=>{setTime(0);setPlaying(false);},[project.style,project.scenes,project.duration]);
 useEffect(()=>{if(canvas.current)drawFrame(canvas.current,scenes,project.style,time,project.duration);},[time,scenes,project.style,project.duration]);
 useEffect(()=>{if(!playing)return;let raf=0;let last=performance.now();const tick=(now:number)=>{const delta=(now-last)/1000;last=now;setTime(t=>{if(t+delta>=project.duration){setPlaying(false);return 0;}return t+delta;});raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf);},[playing,project.duration]);
 useEffect(()=>{if(!audio.current)return;if(playing){audio.current.currentTime=time;audio.current.play().catch(()=>toast.error('Press play on the recording to hear it.'));}else audio.current.pause();},[playing]);
 async function save(p=project){if(!loaded){toast.error('Wait for your workspace to load before saving.');return null;}setBusy('save');try{const value={...p,id:p.id==='new-draft'?crypto.randomUUID():p.id};const saved=await api<Project>('/api/items',jsonOptions({id:value.id,kind:'project',revision:value.revision,value}));setProject(saved);setProjects(old=>[saved,...old.filter(x=>x.id!==saved.id)]);setDirty(false);toast.success('Your video project is saved.');return saved;}catch(e){toast.error((e as Error).message);return null;}finally{setBusy('');}}
 async function openProject(p:Project){if(dirty&&!(await save()))return;setProject(p);setDirty(false);setView('create');setTab(p.scenes.length?'script':'source');}
 async function startNew(){if(dirty&&!(await save()))return;setProject(newProject());setDirty(false);setView('create');setTab('source');}
 async function generate(){if(!project.source.trim()){toast.error('Add your story or idea first.');return;}if(project.sourceType==='script'){change({scenes:scriptScenes(project.source),skillSnapshot:[],status:'ready'});setTab('script');toast.success('Your script is split into scenes. No writing model was used.');return;}if(model.provider==='local'){setBusy('generate');try{const result=await localGenerate(project,model,selected);change({scenes:result,skillSnapshot:selected,status:'ready'});setTab('script');toast.success('Your local model wrote the script.');}catch(e){toast.error((e as Error).message);}finally{setBusy('');}return;}if(!key){toast.error('Add your writing-service key below first.');return;}setBusy('generate');try{const result=await api<{scenes:Scene[],skillSnapshot:Skill[]}>('/api/generate',jsonOptions({project,key}));change({...result,status:'ready'});setTab('script');toast.success('Your script is ready to review.');}catch(e){toast.error((e as Error).message);}finally{setBusy('');}}
 function downloadTask(){const payload={format:'clipforge-task',version:1,project:{...project,skillSnapshot:selected},skills:selected,model,voice:{engine:'kokoro',name:'af_heart'}};downloadBlob(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),'clipforge-task.json');toast.success('Task downloaded. It includes your story and chosen instructions, without service keys.');}
 async function importResult(file:File){try{const raw=JSON.parse(await file.text());const p=ProjectSchema.parse(raw.project||raw);change(p);setTab('script');toast.success('Your script is ready. Add the matching narration file to hear it.');}catch{toast.error('Choose a project JSON file made by ClipForge.');}}
 async function exportVideo(){if(!project.scenes.length)return;setExporting(true);setProgress(0);abortRef.current=new AbortController();try{const video=await recordVideo(project.scenes,project.style,project.duration,audioUrl,setProgress,abortRef.current.signal);downloadBlob(video,(project.title||'clipforge').replace(/[^\p{L}\p{N} -]/gu,'').slice(0,60)+'.webm');toast.success('Your video has downloaded.');}catch(e){toast.error((e as Error).message);}finally{setExporting(false);}}
 async function uploadAudio(file:File){setBusy('audio');try{const data=new FormData();data.append('file',file);const result=await api<{id:string,name:string}>('/api/audio',{method:'POST',body:data});change({audioId:result.id});toast.success('Recording added. Save your project to keep it linked.');}catch(e){toast.error((e as Error).message);}finally{setBusy('');}}
 async function saveSkill(){if(!skillEdit)return;const parsed=SkillSchema.safeParse(skillEdit);if(!parsed.success){toast.error('Give these instructions a name and some text.');return;}setBusy('skill');try{const value={...skillEdit,version:skillEdit.revision?skillEdit.version+1:skillEdit.version};const saved=await api<Skill>('/api/items',jsonOptions({id:value.id,kind:'skill',revision:value.revision,value}));setSkills(s=>[...s.filter(x=>x.id!==saved.id),saved]);setSkillEdit(null);toast.success('Instructions saved. New scripts can use them now.');}catch(e){toast.error((e as Error).message);}finally{setBusy('');}}
 async function removeItem(){if(!remove)return;try{await api('/api/items',jsonOptions({id:remove.item.id,kind:remove.kind,revision:remove.item.revision},'DELETE'));if(remove.kind==='project')setProjects(s=>s.filter(x=>x.id!==remove.item.id));else if(remove.kind==='skill')setSkills(s=>s.filter(x=>x.id!==remove.item.id));else setModels(s=>s.filter(x=>x.id!==remove.item.id));toast.success('Removed from your workspace.');}catch(e){toast.error((e as Error).message);}finally{setRemove(null);}}
 const names={create:'Create a video',projects:'Your videos',skills:'Saved instructions',models:'Models & voices',publish:'Connected accounts',agents:'Agent tools (MCP)'};
 return <SidebarProvider style={{'--sidebar-width':'244px'} as React.CSSProperties}><Toaster richColors position="bottom-right"/><Sidebar className="studio-sidebar"><SidebarHeader><a href="/" className="brand"><span className="brand-icon"><Clapperboard size={23}/></span><span>clipforge<span className="brand-dot">®</span></span></a><span className="workspace-label">YOUR CREATIVE WORKSPACE</span></SidebarHeader><SidebarContent><SidebarMenu>{([{id:'create',name:'Create a video',icon:Plus},{id:'projects',name:'Your videos',icon:FolderOpen},{id:'skills',name:'Saved instructions',icon:BookOpen},{id:'models',name:'Models & voices',icon:SlidersHorizontal},{id:'agents',name:'Agent tools (MCP)',icon:Sparkles},{id:'publish',name:'Connected accounts',icon:Link2}] as const).map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view===n.id} className={'nav-item '+(view===n.id?'active':'')} onClick={()=>setView(n.id)}><n.icon size={19}/><span>{n.name}</span>{n.id==='projects'&&<span className="nav-count">{projects.length}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-tip"><BookOpen size={24}/><strong>Your way of telling it.</strong><p>Save your writing instructions. Your chosen model reads them before making a script.</p><button onClick={()=>setView('skills')}>See your instructions <ArrowRight size={16}/></button></div></SidebarContent><SidebarFooter><button className="local-note" onClick={()=>setGuide(true)}><Monitor size={20}/><span><strong>Use your own computer</strong><small>Local video maker guide</small></span><ArrowUpRight size={16}/></button><div className="account"><span className="avatar">Y</span><div><strong>Your studio</strong><small>Private · early release</small></div><Pill>0.4</Pill></div></SidebarFooter></Sidebar>
 <main className="app-main"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-menu"/><span>Workspace</span><ChevronRight size={14}/><strong>{names[view]}</strong></div><div className="top-actions"><button className="nbs-button theme-toggle" aria-label={theme==='light'?'Use dark colors':'Use light colors'} onClick={()=>{const t=theme==='light'?'dark':'light';setTheme(t);document.documentElement.dataset.theme=t;localStorage.setItem('clipforge-theme',t);}}>{theme==='light'?'Dark':'Light'}</button><span className="save-state">{dirty?'Unsaved changes':loaded?'Workspace ready':'Opening workspace…'}</span>{view==='create'&&<button className="nbs-button button small" disabled={!!busy||!loaded} onClick={()=>save()}><Save size={16}/>{busy==='save'?'Saving…':'Save draft'}</button>}</div></header>
 {loadError&&<div className="error-banner" role="alert"><span>{loadError}</span><button onClick={refresh}><RefreshCw size={15}/>Try again</button></div>}
 <div className="main-content">
 {view==='create'&&<><div className="page-heading"><div><div className="eyebrow">FROM IDEA TO VIDEO</div><h1>Make your next video<span className="purple-text">.</span></h1><p>A story, your instructions, a little motion. Start here.</p></div><button className="text-button" onClick={startNew}><Plus size={17}/>New project</button></div>
 <div className="editor-grid"><section className="editor-panel"><fieldset disabled={!!busy} className="editor-fields"><Tabs value={tab} onValueChange={setTab}><TabsList className="workflow-tabs"><TabsTrigger value="source"><span>1</span>Your story</TabsTrigger><TabsTrigger value="script"><span>2</span>Script & voice</TabsTrigger><TabsTrigger value="export"><span>3</span>Make the video</TabsTrigger></TabsList>
 <TabsContent value="source"><div className="panel-inner"><Field label="Give your video a name" help="Only you see this project name until you choose to share it."><input value={project.title} maxLength={100} onChange={e=>change({title:e.target.value})} placeholder="For example, My first story"/></Field>
 <Field label="What are you starting with?" help="Choose a story to rewrite, a new idea, or a finished script to keep as written." details={<p>Story: rewrite text you supply. Idea: write something new from your brief. Finished script: split your words into scenes without asking a writing model.</p>}><Choice label="Starting material" value={project.sourceType} onChange={v=>change({sourceType:v as Project['sourceType']})} options={[{value:'story',label:'A story or article · recommended'},{value:'idea',label:'An idea for something new'},{value:'script',label:'A finished script'}]}/></Field>
 <Field label={project.sourceType==='idea'?'What should this video be about?':'Paste your words here'} help="Use your own words or text you have permission to adapt. Paste the article text itself; link reading is available in the local maker."><textarea className="source-text" value={project.source} maxLength={18000} onChange={e=>change({source:e.target.value})} placeholder={project.sourceType==='idea'?'For example: A 45-second story about a lost letter that arrives 20 years late.':'Paste a story, article or script…'}/></Field><div className="under-input"><button className="text-button" onClick={()=>sourceFile.current?.click()}><Upload size={14}/>Choose a text file</button><button className="text-button" onClick={()=>{change({title:'One small moment',source:demo.map(s=>s.narration).join('\n\n'),sourceType:'script'});}}>Try an example <ArrowUpRight size={14}/></button></div><input ref={sourceFile} hidden type="file" accept=".txt,.md" onChange={async e=>{const f=e.target.files?.[0];if(f){if(f.size>60000)toast.error('Choose a text file smaller than 60 KB.');else change({source:(await f.text()).slice(0,18000)});}e.target.value='';}}/>
 <div className="section-label"><h2>Choose the look</h2><span>You can change this later.</span></div><div className="style-options">{styles.map(s=><button key={s.id} className={'style-option '+(project.style===s.id?'selected':'')} onClick={()=>change({style:s.id})} aria-pressed={project.style===s.id}><div className={'style-sample '+s.color}><span>{s.id==='story'?'Once upon\na scroll.':s.id==='explainer'?'One idea.\nMade simple.':'Make every\nword count.'}</span><div className="mini-lines"/></div><strong>{s.name}</strong>{project.style===s.id&&<span className="style-check"><Check size={12}/></span>}</button>)}</div><p className="helper">{styles.find(s=>s.id===project.style)?.description} Story cards are a good first choice.</p>
 <div className="two-cols"><Field label="Video length" help="Aim for a short video. An uploaded recording sets the final length." details={<p>15 seconds: one quick thought. 45 seconds: a short story (recommended). 120 seconds: a longer explanation. Allowed: 15–120 seconds.</p>}><Choice label="Video length" value={String(project.duration)} onChange={v=>change({duration:Number(v)})} options={[15,30,45,60,90,120].map(n=>({value:String(n),label:n+' seconds'+(n===45?' · recommended':'')}))}/></Field><Field label="Who writes the script?" help="Use your computer, or a writing service you already have."><Choice label="Writing model" value={project.modelId} onChange={v=>change({modelId:v})} options={models.filter(m=>modelTask(m)==='script').map(m=>({value:m.id,label:m.name}))}/></Field></div>
 <div className="skill-strip"><div className="setting-row"><div><strong>Choose instructions for me</strong><p className="helper">Read matching instructions before writing this script.</p></div><Switch checked={project.autoSkills} onCheckedChange={v=>change({autoSkills:v})} aria-label="Choose instructions for me"/></div><div className="skill-pills">{selected.length?selected.map(s=><Pill key={s.id} tone="purple"><BookOpen size={12}/>{s.name}</Pill>):<span className="helper">No match. The writer will use the basic script instructions.</span>}</div>{!project.autoSkills&&<div className="check-list">{skills.filter(s=>s.enabled).map(s=><label key={s.id}><Checkbox checked={project.skillIds.includes(s.id)} onCheckedChange={v=>change({skillIds:v?[...project.skillIds,s.id]:project.skillIds.filter(id=>id!==s.id)})}/>{s.name}</label>)}</div>}<details className="details"><summary>What happens when I change this?</summary><p>On: match instructions by topic and video style. Off: use only the instructions you select. Leave this on for fewer steps. For example, a story can use “A story worth finishing.”</p></details></div>
 {model?.provider!=='local'&&project.sourceType!=='script'&&<Field label="Your writing-service key" help="Used only for this request. It is not saved. Your service may charge for writing; check your allowance first."><input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder="Paste the key from your writing service"/></Field>}
 <button className="nbs-button nbs-button--primary button primary full" disabled={!!busy||!project.source.trim()} onClick={generate}>{busy==='generate'?<LoaderCircle className="spin" size={18}/>:<Sparkles size={18}/>} {busy==='generate'?'Reading instructions and writing…':project.sourceType==='script'?'Use this script':'Write my script'}<ArrowRight size={18}/></button><p className="button-help">{project.sourceType==='script'?'Keep your words and arrange them into editable scenes.':model?.provider==='local'?'Your local LM Studio model reads the selected instructions and writes the script here.':'Sends this story and your selected instructions to your writing service.'}</p>
 </div></TabsContent>
 <TabsContent value="script"><div className="panel-inner"><div className="section-label"><h2>Give every scene a purpose</h2><button className="text-button" onClick={()=>bundleFile.current?.click()}><Upload size={14}/>Import local result</button></div><input ref={bundleFile} hidden type="file" accept=".json" onChange={e=>{const f=e.target.files?.[0];if(f&&f.size<200000)importResult(f);else if(f)toast.error('Choose a project file smaller than 200 KB.');e.target.value='';}}/>
 {!project.scenes.length?<div className="empty"><FileText size={32}/><h3>Your script will appear here.</h3><p>Start with your story, or try the example to explore the editor.</p><button className="nbs-button button" onClick={()=>{change({title:'One small moment',sourceType:'script',source:demo.map(s=>s.narration).join('\n\n'),scenes:demo,status:'ready'});}}>Use the example script</button></div>:<><div className="skill-pills">{project.skillSnapshot.length?project.skillSnapshot.map(s=><Pill key={s.id} tone="purple"><BookOpen size={12}/>{s.name} · v{s.version}</Pill>):<Pill>Your words · no writing model used</Pill>}</div><p className="helper">These are the instructions recorded when this script was made. Edits below are saved when you select Save draft.</p>{project.scenes.map((s,i)=><article className="scene-editor" key={i}><div className="scene-top"><span className="scene-num">{String(i+1).padStart(2,'0')}</span><strong>Scene {i+1}</strong><button className="icon-button" aria-label={'Remove scene '+(i+1)} onClick={()=>change({scenes:project.scenes.filter((_,n)=>n!==i)})}><Trash2 size={15}/></button></div><Field label="Words on screen" help="A short heading viewers can read at a glance."><input value={s.heading} maxLength={120} onChange={e=>change({scenes:project.scenes.map((v,n)=>n===i?{...v,heading:e.target.value}:v)})}/></Field><Field label="Words to speak" help="This text becomes the captions and narration."><textarea value={s.narration} maxLength={1200} onChange={e=>change({scenes:project.scenes.map((v,n)=>n===i?{...v,narration:e.target.value}:v)})}/></Field></article>)}<button className="nbs-button button full" disabled={project.scenes.length>=16} onClick={()=>change({scenes:[...project.scenes,{heading:'A new scene',narration:'Write the next part of your story.'}]})}><Plus size={16}/>Add a scene</button><p className="helper">Up to 16 scenes per video. Three to six is a good start.</p></>}
 <div className="audio-section"><h2><Volume2 size={20}/> Add the voice</h2><p>Upload your recording, or generate narration with the voice selected in Models & voices.</p><button className="nbs-button" onClick={()=>setView('models')}>Choose models and generate voice</button><label className="nbs-button button"><Upload size={16}/>{busy==='audio'?'Adding recording…':'Choose a recording'}<input hidden type="file" accept="audio/*" disabled={!!busy} onChange={e=>{const f=e.target.files?.[0];if(f)uploadAudio(f);e.target.value='';}}/></label><p className="helper">MP3, WAV, M4A, OGG or WebM · up to 20 MB. A clear recording under two minutes works best.</p>{audioUrl&&<><audio ref={audio} controls src={audioUrl} onLoadedMetadata={e=>{const d=e.currentTarget.duration;if(d>180){toast.error('Choose a recording shorter than three minutes.');}else if(Number.isFinite(d)){change({duration:Math.max(15,Math.min(120,Math.round(d)))})}}}/><button className="text-button" onClick={async()=>{try{await api('/api/audio?id='+project.audioId,{method:'DELETE'});change({audioId:undefined});}catch(e){toast.error((e as Error).message);}}}>Remove recording</button></>}</div><button className="nbs-button nbs-button--primary button primary full" disabled={!project.scenes.length} onClick={()=>setTab('export')}>Review the video <ArrowRight size={17}/></button></div></TabsContent>
 <TabsContent value="export"><div className="panel-inner"><Pill tone="lime">YOUR WORDS, IN MOTION</Pill><h2 className="export-title">Ready for a first look?</h2><p>Play the preview, check your words, then save a video to your device.</p><div className="export-specs"><div><strong>9:16</strong><span>Vertical video</span></div><div><strong>720p</strong><span>Browser export</span></div><div><strong>{project.duration}s</strong><span>Target length</span></div></div><div className="notice"><Volume2 size={21}/><div><strong>{audioUrl?'Your recording is included.':'This video has no voice yet.'}</strong><p>{audioUrl?'Captions are paced across the recording, not aligned word by word. Check the timing before sharing.':'Add a recording in Script & voice, or use the local maker for generated narration. You can still save a silent video.'}</p></div></div>
 <button className="nbs-button nbs-button--primary button primary full" disabled={exporting||!project.scenes.length||project.scenes.some(s=>!s.heading.trim()||!s.narration.trim())} onClick={exportVideo}><Download size={18}/>{exporting?'Making your video…':'Download video'}</button><p className="button-help">Saves a WebM video. Keep this tab open and visible until it finishes. Saving takes about as long as the video.</p>{exporting&&<div className="export-progress"><Progress value={progress}/><div><span>{Math.round(progress)}% complete</span><button className="text-button" onClick={()=>abortRef.current?.abort()}>Stop saving</button></div></div>}
 <div className="divider"/><h3>Want an MP4 with a generated voice?</h3><p>The local maker uses your selected writing model, Kokoro narration and motion templates. It can watch a folder and make videos automatically.</p><button className="nbs-button button full" onClick={downloadTask}><Monitor size={18}/>Download task for my computer</button><button className="text-button" onClick={()=>setGuide(true)}>Read the local maker guide <ArrowUpRight size={15}/></button><p className="helper">Task files include your source text and instructions. Service keys stay on your computer. Nothing is posted to social accounts.</p></div></TabsContent>
 </Tabs></fieldset></section>
 <aside className="preview-column"><div className="preview-heading"><strong>THE PREVIEW</strong><Pill>{project.scenes.length?'Your script':'Style example'}</Pill></div><div className="preview-stage"><canvas ref={canvas} width={540} height={960} aria-label="Animated vertical video preview"/><div className="preview-player"><button onClick={()=>setPlaying(p=>!p)} aria-label={playing?'Pause preview':'Play preview'}>{playing?<Pause size={17}/>:<Play size={17}/>}</button><span>0:{String(Math.floor(time)).padStart(2,'0')} / {Math.floor(project.duration/60)}:{String(project.duration%60).padStart(2,'0')}</span><span>9:16</span></div></div><p className="preview-caption">{project.scenes.length?'Changes to your words and style appear here.':'An example of this style. Your own script will replace it.'}</p><div className="recipe-card"><div className="recipe-heading"><Sparkles size={17}/><strong>Your video recipe</strong></div><div><span>Writing</span><strong>{project.sourceType==='script'?'Your finished script':model?.name}</strong></div><div><span>Instructions</span><strong>{project.sourceType==='script'?'Your script is kept':selected.length+' selected'}</strong></div><div><span>Look</span><strong>{styles.find(s=>s.id===project.style)?.name}</strong></div><div><span>Voice</span><strong>{audioUrl?'Your recording':'Not added yet'}</strong></div><div className="recipe-footer"><CheckCircle2 size={15}/>You review before sharing.</div></div></aside></div></>}
 {view==='projects'&&<><div className="page-heading"><div><div className="eyebrow">PICK UP WHERE YOU LEFT OFF</div><h1>Your videos<span className="purple-text">.</span></h1><p>Saved stories, scripts and styles, all in one place.</p></div><button className="nbs-button nbs-button--primary button primary" onClick={startNew}><Plus size={17}/>Create a video</button></div><input className="search" aria-label="Find a video by name" placeholder="Find a video by name…" value={search} onChange={e=>setSearch(e.target.value)}/>{!projects.length?<div className="empty panel"><FolderOpen size={38}/><h2>Your first video starts with a story.</h2><p>Create a project and save it. You can come back and keep working here.</p><button className="nbs-button nbs-button--primary button primary" onClick={startNew}>Create your first video <ArrowRight size={16}/></button></div>:<div className="project-grid">{projects.filter(p=>p.title.toLowerCase().includes(search.toLowerCase())).map(p=><article className="project-card" key={p.id}><button className={'project-cover '+(p.style==='story'?'purple':p.style==='explainer'?'lime':'dark')} onClick={()=>openProject(p)}><span>{p.scenes[0]?.heading||p.title}</span><Pill>{p.duration} seconds</Pill></button><div className="project-info"><h3>{p.title}</h3><p>{p.scenes.length?p.scenes.length+' scenes · script ready':'Draft · add your story'}</p><div><button className="text-button" onClick={()=>openProject(p)}>Open project <ArrowRight size={15}/></button><button className="icon-button" onClick={()=>setRemove({kind:'project',item:p})} aria-label={'Delete '+p.title}><Trash2 size={16}/></button></div></div></article>)}</div>}</>}
 {view==='skills'&&<><div className="page-heading"><div><div className="eyebrow">TEACH IT YOUR WAY</div><h1>Saved instructions<span className="purple-text">.</span></h1><p>Tell the writer what good looks like. It reads these before it writes.</p></div><div className="actions"><button className="nbs-button button" onClick={()=>skillFile.current?.click()}><Upload size={17}/>Import instructions</button><button className="nbs-button nbs-button--primary button primary" onClick={()=>setSkillEdit({id:crypto.randomUUID(),name:'',description:'',tags:'story',instructions:'',enabled:true,version:1})}><Plus size={17}/>Add instructions</button></div></div><input ref={skillFile} hidden type="file" accept=".md,.txt" onChange={async e=>{const f=e.target.files?.[0];if(f&&f.size<=60000){const text=await f.text();setSkillEdit({id:crypto.randomUUID(),name:f.name.replace(/\.(md|txt)$/i,'').slice(0,80),description:'Imported writing instructions',tags:'story',instructions:text.slice(0,18000),enabled:true,version:1});}else if(f)toast.error('Choose a file smaller than 60 KB.');e.target.value='';}}/>
 <div className="notice lavender"><BookOpen size={22}/><div><strong>A skill is a set of reusable instructions.</strong><p>For example: “Start with a surprising question. Use short sentences. End with one useful takeaway.” Import a SKILL.md file or write your own.</p></div></div><div className="skills-grid">{skills.map((s,i)=><article className="skill-card" key={s.id}><div className="card-top"><span className={'card-icon '+(i%2?'lime':'purple')}><BookOpen size={23}/></span><Pill tone={s.enabled?'lime':'plain'}>{s.enabled?'Available to the writer':'Turned off'}</Pill></div><h2>{s.name}</h2><p>{s.description}</p><div className="skill-tags">{s.tags.split(',').filter(Boolean).slice(0,4).map(t=><span key={t}>{t.trim()}</span>)}</div><div className="card-bottom"><span>Version {s.version}</span><button className="text-button" onClick={()=>setSkillEdit({...s})}>Read & edit <ArrowUpRight size={16}/></button></div></article>)}</div></>}
 {view==='models'&&<ModelWorkbench models={models} project={project} onProject={change} onModels={setModels}/>}
 {view==='agents'&&<><div className="page-heading"><div><div className="eyebrow">TOOLS FOR YOUR ASSISTANT</div><h1>Agent tools (MCP)</h1><p>Let an assistant inspect your projects and discover saved instructions before writing.</p></div></div><div className="nbs-card integration-panel"><h2>ClipForge tool server</h2><p>The included local MCP server lets Hermes and other MCP clients discover skills, list LM Studio models and write a script with selected instructions. It runs on the same computer as LM Studio.</p><button className="nbs-button" onClick={()=>downloadBlob(new Blob([JSON.stringify({mcpServers:{clipforge:{command:'python',args:['worker/agent_server.py']} }},null,2)],{type:'application/json'}),'clipforge-mcp.json')}>Download agent connection example</button><p className="helper">Run from the ClipForge source folder, or replace the script path with its full path. Install worker/requirements-agent.txt first. No service key is included.</p></div><div className="notice"><BookOpen size={22}/><div><strong>Instructions first, generation second.</strong><p>Agents discover available skills, select them, then generate. Tool results include the instruction versions used. Download a project task to pass your saved instructions to the local server.</p></div></div><div className="nbs-card integration-panel"><h2>External MCP tools</h2><p>Connect external tool servers in your agent harness, alongside ClipForge. The web editor does not execute arbitrary MCP tools or install executable skill packages. Publishing tools retain their own account permissions.</p></div></>}
 {view==='publish'&&<><div className="page-heading"><div><div className="eyebrow">SHARE WHEN YOU ARE READY</div><h1>Connected accounts<span className="purple-text">.</span></h1><p>For now, download your video and upload it to your channel.</p></div></div><div className="nbs-card panel empty"><Link2 size={36}/><h2>Account connections are coming next.</h2><p>This release does not connect or post to YouTube, TikTok or Instagram. No social-account passwords are collected.</p><button className="nbs-button nbs-button--primary button primary" onClick={()=>{setView('create');setTab('export');}}>Open video downloads <ArrowRight size={17}/></button></div><div className="notice"><CheckCircle2 size={23}/><div><strong>You stay in control of posting.</strong><p>The planned connection will let you sign in with the platform, choose a channel, and decide whether each video needs review. Platform approval is still required before this can launch.</p></div></div></>}
 </div><footer className="app-footer"><span>Made with your ideas. Shaped by your instructions.</span><span>ClipForge Studio · Early release</span></footer></main>
 <Dialog open={!!skillEdit} onOpenChange={v=>{if(!v)setSkillEdit(null)}}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>{skillEdit?.revision?'Edit instructions':'Add writing instructions'}</DialogTitle><DialogDescription>Tell the writer what to do and when to use these instructions.</DialogDescription></DialogHeader>{skillEdit&&<div className="dialog-fields"><Field label="Name" help="Choose a name you will recognize, like Short horror story."><input value={skillEdit.name} maxLength={80} onChange={e=>setSkillEdit({...skillEdit,name:e.target.value})}/></Field><Field label="What are these instructions for?" help="One sentence that explains the result you want."><input value={skillEdit.description} maxLength={240} onChange={e=>setSkillEdit({...skillEdit,description:e.target.value})}/></Field><Field label="Matching topics" help="Separate topics with commas. Example: story, horror, fiction. Include story, explainer or quote to match that style."><input value={skillEdit.tags} maxLength={300} onChange={e=>setSkillEdit({...skillEdit,tags:e.target.value})}/></Field><Field label="What should the writer do?" help="Describe the structure, tone and examples. These instructions guide writing; they cannot run code or change your accounts."><textarea rows={7} value={skillEdit.instructions} maxLength={18000} onChange={e=>setSkillEdit({...skillEdit,instructions:e.target.value})} placeholder="Start with… Keep the language… End with…"/></Field><div className="setting-row"><strong>Let the writer use these instructions</strong><Switch checked={skillEdit.enabled} onCheckedChange={v=>setSkillEdit({...skillEdit,enabled:v})}/></div><p className="helper">On: available for new scripts. Off: kept here but not used. Leave on for instructions you want to use. Existing scripts keep their original instruction version.</p><button className="nbs-button nbs-button--primary button primary full" disabled={!!busy} onClick={saveSkill}><Save size={16}/>{busy==='skill'?'Saving…':'Save instructions'}</button></div>}</DialogContent></Dialog>
 <Dialog open={guide} onOpenChange={setGuide}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>Make videos on your computer</DialogTitle><DialogDescription>Your computer does the writing, narration and rendering. It must stay on while making videos.</DialogDescription></DialogHeader><ol className="guide-steps"><li><strong>Get the ClipForge source download.</strong><p>Open the worker folder. Its README walks you through Python, FFmpeg and the optional Kokoro voice download.</p></li><li><strong>Start your model in LM Studio.</strong><p>Start its local server. ClipForge checks the usual address automatically. Enable browser access (CORS) in LM Studio if the browser cannot connect. A finished script needs no writing model.</p></li><li><strong>Download a task from this editor.</strong><p>It contains your story, style and selected instruction versions.</p></li><li><strong>Run the local maker.</strong><p>It writes an MP4, narration, captions and a project file. A folder-watch option processes new tasks automatically.</p></li></ol><div className="notice"><FileText size={20}/><p>The hosted editor and local maker exchange files in this release. They are not continuously connected. The local maker does not publish to social accounts.</p></div></DialogContent></Dialog>
 <AlertDialog open={!!remove} onOpenChange={v=>{if(!v)setRemove(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this saved item?</AlertDialogTitle><AlertDialogDescription>{remove?.item.title||remove?.item.name} will be removed from this workspace. This cannot be undone. Downloaded files stay on your device.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep it</AlertDialogCancel><AlertDialogAction onClick={removeItem}>Delete it</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </SidebarProvider>;
}
