import { sceneDuration, type Scene } from './core';
export const palettes={story:{bg:'#b9a1ed',ink:'#17151c',accent:'#e3fd78'},explainer:{bg:'#e3fd78',ink:'#17151c',accent:'#b9a1ed'},quote:{bg:'#202127',ink:'#fffdf5',accent:'#ffd16e'}};
function wrap(ctx:CanvasRenderingContext2D,text:string,width:number){const lines:string[]=[];let line='';for(const word of text.split(/\s+/)){const test=line?line+' '+word:word;if(ctx.measureText(test).width>width&&line){lines.push(line);line=word;}else line=test;}if(line)lines.push(line);return lines;}
export function drawFrame(canvas:HTMLCanvasElement,scenes:Scene[],style:keyof typeof palettes,time:number,duration:number){
 const ctx=canvas.getContext('2d');if(!ctx)return;const w=canvas.width,h=canvas.height;const scale=w/540;ctx.save();ctx.scale(scale,scale);const H=h/scale;const p=palettes[style];
 ctx.fillStyle=p.bg;ctx.fillRect(0,0,540,H);ctx.strokeStyle=p.ink;ctx.lineWidth=2;ctx.globalAlpha=.1;for(let x=-50;x<600;x+=48){ctx.beginPath();ctx.moveTo(x+time*2%48,0);ctx.lineTo(x+time*2%48,H);ctx.stroke();}ctx.globalAlpha=1;
 let index=0,elapsed=0;for(let i=0;i<scenes.length;i++){const d=sceneDuration(scenes[i],scenes,duration);if(time<elapsed+d||i===scenes.length-1){index=i;break;}elapsed+=d;}
 const s=scenes[index]||{heading:'Your story starts here',narration:'Add a story. Choose a style. Make it yours.'};const d=scenes.length?sceneDuration(s,scenes,duration):duration;const local=Math.max(0,time-elapsed);const enter=Math.min(1,local/.45);const offset=(1-Math.pow(enter,3))*24;
 ctx.fillStyle=p.ink;ctx.font='bold 16px Arial';ctx.fillText(style.toUpperCase()+' / '+String(index+1).padStart(2,'0'),36,58);ctx.fillRect(36,80,468,3);
 ctx.save();ctx.translate(0,offset);ctx.fillStyle=p.ink;ctx.font='900 47px Arial';const heading=wrap(ctx,s.heading,452).slice(0,4);heading.forEach((line,i)=>ctx.fillText(line,40,190+i*54));
 const words=s.narration.split(/\s+/);const active=Math.min(words.length-1,Math.floor(local/Math.max(d,.1)*words.length));const page=Math.floor(active/18);const text=words.slice(page*18,page*18+18).join(' ');ctx.font='bold 27px Arial';const lines=wrap(ctx,text,388).slice(0,8);const boxH=Math.max(180,lines.length*38+64),y=Math.max(420,Math.min(555,H-boxH-110));
 ctx.fillStyle=p.ink;ctx.fillRect(48,y+8,452,boxH);ctx.fillStyle=p.accent;ctx.fillRect(40,y,452,boxH);ctx.strokeStyle=p.ink;ctx.lineWidth=3;ctx.strokeRect(40,y,452,boxH);ctx.fillStyle='#17151c';lines.forEach((line,i)=>ctx.fillText(line,70,y+54+i*38));ctx.restore();
 ctx.fillStyle=p.ink;ctx.font='bold 14px Arial';ctx.fillText('●',40,H-52);ctx.fillText(String(index+1).padStart(2,'0')+' / '+String(Math.max(1,scenes.length)).padStart(2,'0'),66,H-52);ctx.globalAlpha=.18;ctx.fillRect(36,H-29,468,5);ctx.globalAlpha=1;ctx.fillRect(36,H-29,468*Math.min(1,time/duration),5);ctx.restore();
}
export function downloadBlob(blob:Blob,name:string){const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),20000);}
export async function recordVideo(scenes:Scene[],style:keyof typeof palettes,duration:number,audioUrl:string|undefined,onProgress:(n:number)=>void,signal:AbortSignal){
 if(typeof MediaRecorder==='undefined')throw Error('This browser cannot save video. Use a recent Chrome or download the local task.');
 const canvas=document.createElement('canvas');canvas.width=720;canvas.height=1280;const stream=canvas.captureStream(30);let audio:AudioContext|undefined;let source:AudioBufferSourceNode|undefined;
 try{if(audioUrl){audio=new AudioContext();const response=await fetch(audioUrl);if(!response.ok)throw Error('Your recording could not be opened. Upload it again.');const buffer=await audio.decodeAudioData(await response.arrayBuffer());if(buffer.duration>180)throw Error('Choose a recording shorter than three minutes.');duration=buffer.duration;const dest=audio.createMediaStreamDestination();source=audio.createBufferSource();source.buffer=buffer;source.connect(dest);dest.stream.getAudioTracks().forEach(t=>stream.addTrack(t));await audio.resume();}
 const mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(m=>MediaRecorder.isTypeSupported(m));if(!mime)throw Error('WebM saving is unavailable. Download the task for the local video maker.');
 const recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:3000000});const chunks:BlobPart[]=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};
 await new Promise<void>((resolve,reject)=>{let raf=0;const cleanup=()=>{cancelAnimationFrame(raf);document.removeEventListener('visibilitychange',hidden);signal.removeEventListener('abort',abort);};const abort=()=>{cleanup();if(recorder.state!=='inactive')recorder.stop();reject(Error('Video saving stopped. Your project is still saved.'));};const hidden=()=>{if(document.hidden)abort();};document.addEventListener('visibilitychange',hidden);signal.addEventListener('abort',abort,{once:true});recorder.onerror=()=>{cleanup();reject(Error('Video saving failed. Try again or use the local video maker.'));};recorder.onstop=()=>{cleanup();resolve();};drawFrame(canvas,scenes,style,0,duration);recorder.start(250);source?.start();const start=performance.now();const frame=()=>{const t=(performance.now()-start)/1000;drawFrame(canvas,scenes,style,Math.min(t,duration),duration);onProgress(Math.min(100,t/duration*100));if(t>=duration){recorder.stop();}else raf=requestAnimationFrame(frame);};raf=requestAnimationFrame(frame);if(signal.aborted)abort();});
 return new Blob(chunks,{type:mime});
 }finally{try{source?.stop();}catch{}stream.getTracks().forEach(t=>t.stop());await audio?.close();}
}
