import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {pathToFileURL} from 'node:url';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
const dir=await mkdtemp(path.join(tmpdir(),'clipforge-test-'));
const outfile=path.join(dir,'core.mjs');
await build({entryPoints:['lib/core.ts'],outfile,bundle:true,platform:'node',format:'esm'});
const c=await import(pathToFileURL(outfile));
const p={...c.newProject(),source:'A horror story',style:'story'};
test('discovers and reads relevant skills',()=>{const skills=c.chooseSkills(c.defaultSkills,p);assert.equal(skills[0].id,'builtin-story');assert.ok(c.generationMessages(p.source,p.style,45,skills)[0].content.includes(skills[0].instructions));});
test('disabled skills cannot be pinned',()=>assert.deepEqual(c.chooseSkills(c.defaultSkills.map(s=>({...s,enabled:false})),{...p,autoSkills:false,skillIds:['builtin-story']}),[]));
test('pin order survives selection',()=>assert.deepEqual(c.chooseSkills(c.defaultSkills,{...p,autoSkills:false,skillIds:['builtin-quote','builtin-story']}).map(s=>s.id),['builtin-quote','builtin-story']));
test('malformed model responses fail validation',()=>assert.throws(()=>c.parseScenes('{"scenes":[{"heading":"Missing narration"}]}')));
test('JSON code fences are supported',()=>assert.equal(c.parseScenes('```json\n{"scenes":[{"heading":"Hi","narration":"Hello"}]}\n```').length,1));
test('source script retains paragraphs',()=>assert.equal(c.scriptScenes('One.\n\nTwo.').length,2));
test('project schema rejects invalid duration',()=>assert.equal(c.ProjectSchema.safeParse({...p,duration:0}).success,false));
test('model profiles do not persist service keys',()=>assert.equal('key' in c.ModelSchema.parse({name:'Writer',provider:'local',model:'qwen',key:'private'}),false));
test('legacy writing profiles remain compatible',()=>assert.equal(c.modelTask(c.ModelSchema.parse({name:'Old',provider:'groq',model:'x'})),'script'));
test('text models cannot route to voice generation',()=>assert.equal(c.supportsTask({provider:'local',task:'voice'},'voice'),false));
test('voice models cannot route to script generation',()=>assert.equal(c.supportsTask({provider:'elevenlabs',task:'script'},'script'),false));
test('independent model choices survive project save',()=>{const saved=c.ProjectSchema.parse({...p,voiceModelId:'voice',momentModelId:'moments'});assert.equal(saved.voiceModelId,'voice');assert.equal(saved.momentModelId,'moments');});
const momentsFile=path.join(dir,'moments.mjs');await build({entryPoints:['lib/moments.ts'],outfile:momentsFile,bundle:true,platform:'node',format:'esm'});const mc=await import(pathToFileURL(momentsFile));
const segments=[{start:0,end:15,text:'Opening'},{start:15,end:30,text:'Payoff'}];
test('moments reject invented boundaries',()=>assert.throws(()=>mc.parseMoments(JSON.stringify({moments:[{start:1,end:20,title:'Bad',reason:''}]}),segments)));
test('moments preserve real transcript boundaries',()=>assert.equal(mc.parseMoments(JSON.stringify({moments:[{start:0,end:30,title:'Good',reason:'Complete thought'}]}),segments).moments[0].end,30));
test('overlapping transcript segments fail',()=>assert.equal(mc.Transcript.safeParse([{start:0,end:20,text:'a'},{start:15,end:30,text:'b'}]).success,false));
const providersFile=path.join(dir,'providers.mjs');await build({entryPoints:['lib/providers.ts'],outfile:providersFile,bundle:true,platform:'node',format:'esm'});const pc=await import(pathToFileURL(providersFile));
test('cloud model cannot override destination with a custom URL',()=>assert.equal(pc.cloudBase({provider:'openai',baseUrl:'https://evil.example'}),'https://api.openai.com/v1'));
test('cloud speech uses explicit provider auth and no redirect',async()=>{const original=global.fetch;let observed;global.fetch=async(url,options)=>{observed={url,options};return new Response('audio');};try{await pc.providerRequest('https://api.elevenlabs.io/v1/text-to-speech/voice','test-key',{text:'hi'},true);assert.equal(observed.options.headers['xi-api-key'],'test-key');assert.equal(observed.options.redirect,'error');assert.equal(observed.options.headers.Authorization,undefined);}finally{global.fetch=original;}});
